# ============================================================
# Deployment backend
# ============================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: stephanparichon/epsi-k8s-bff:1.0
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: admin-token
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
